PortfolioBundle\Entity\Projets:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\ProjetsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        image:
            type: string
            length: 255
        url:
            type: string
            length: 255
        descritpion:
            type: text
    lifecycleCallbacks: {  }
