PortfolioBundle\Entity\Veille:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\VeilleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        image:
            type: string
            length: 255
        url:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks: {  }
