portfolio_veille:
    resource: "@PortfolioBundle/Resources/config/routing/veille.yml"
    prefix:   /veille

portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Front:index }
