<?php

namespace PortfolioBundle\Repository;

/**
 * VeilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeilleRepository extends \Doctrine\ORM\EntityRepository
{
}
